---
- name: Install nfs-kernel-server for nfs server.
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: true
  when: nfs_server


- name: Install nfs-common for nfs client.
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: true
  when: not nfs_server