---
- name: Install nfs utils.
  ansible.builtin.package:
    name: nfs-utils
    state: present
    update_cache: true


- name: Enable and start rpcbind
  ansible.builtin.systemd:
    name: rpcbind
    state: started
    enabled: true