---
- name: Create exports folder.
  ansible.builtin.file:
    path: "{{ exports_folder }}"
    state: directory
    mode: 0755

- name: Create exports data folder.
  ansible.builtin.file:
    path: "{{ exports_folder }}/{{ data_folder_name }}"
    state: directory
    mode: 0755

- name: Mount and bind data folder. Also configures fstab
  ansible.posix.mount:
    path: "{{ exports_folder }}/{{ data_folder_name }}"
    src: "{{ src_data_folder }}"
    opts: bind
    state: mounted
    fstype: "{{ src_filesystem_type }}"

- name: Copy exports file.
  ansible.builtin.template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Start and enable nfs service with reloaded config.
  ansible.builtin.systemd:
    name: "{{ nfs_server_daemon }}"
    state: started
    enabled: true
    daemon_reload: true
